### ISSUE TITLE
wrong tag for composer

### ISSUE THREAD

**Issue by MarcusWolschon** [r3c/custom_from#20] opened 2020-09-06 16:08 UTC
**Error:**
`"composer require r3c/custom-from"   

  Could not find a matching version of package r3c/custom-from. Check the package spelling, your version constraint and that the package is available in a
   stability which matches your minimum-stability (stable).
`

**Cause:**
The version is tagged "1.3" while according to
https://getcomposer.org/doc/articles/versions.md#tags
it should be tagged "v1.3" for composer to accept this as a stable version.

**Comment by r3c** [comment] 2020-09-06 20:46
I'm not sure this is caused by missing "v" in tag name, however Packagist doesn't seem to trigger its Git hook when a tag is added on an old commit. I just pushed tag [1.6.2](https://github.com/r3c/custom_from/releases/tag/1.6.2) and it [appear properly](https://packagist.org/packages/r3c/custom-from#1.6.2) now and seems to be working fine with composer.

Would you mind having another try with this version?

**Comment by r3c** [comment] 2020-09-13 14:19
@MarcusWolschon can I safely close this issue?

**Comment by MarcusWolschon** [comment] 2020-09-14 06:13
I can give it a try later this week.

**Comment by YiffyToys** [comment] 2020-09-14 19:01
` >composer require r3c/custom-from
Using version ^1.6 for r3c/custom-from
./composer.json has been updated
Loading composer repositories with package information

Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading r3c/custom-from (dev-master 0e33b15 => 1.6.2):  Checking out 2020f447ff
`

This time it worked.
No idea why

**Closed** 2020-09-17 12:59 UTC
